[versions]
agp = "8.13.2"
androidDocumentationPlugin = "2.1.0"
kotlin = "2.3.10"
coreKtx = "1.17.0"
appcompat = "1.7.1"
ksp = "2.3.4"
moshi = "1.15.2"
javaWebSocket = "1.6.0"
coroutines = "1.10.2"
okhttp = "5.3.2"


[libraries]
android-documentation-plugin = { group = "org.jetbrains.dokka", name = "android-documentation-plugin", version.ref = "androidDocumentationPlugin" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
moshi = { group = "com.squareup.moshi", name = "moshi", version.ref = "moshi" }
moshi-codegen = { group = "com.squareup.moshi", name = "moshi-kotlin-codegen", version.ref = "moshi" }
coroutines = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "coroutines" }
java-websocket = { group = "org.java-websocket", name = "Java-WebSocket", version.ref = "javaWebSocket" }
okhttp = { group = "com.squareup.okhttp3", name = "okhttp", version.ref = "okhttp" }


[plugins]
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
